# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    slack.endpoint: https://hooks.slack.com/services/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
    
services:
    slack.messenger.api:
        class:   AppBundle\Api\SlackMessengerApi
        arguments: ["%slack.endpoint%"]